name: pr-unit-tests
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Start containers
      - uses: actions/checkout@v2
      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer--${{ hashFiles('**/composer.lock') }}
        run: make setup-tests
      - name: Run tests
        run: make run-tests